# Development

name = "nft-storage-dev"
main = "./dist/worker.js"
account_id = "fffa4b4363a7e5250af8357087263b3a"
workers_dev = true

# Compatibility flags https://github.com/cloudflare/wrangler/pull/2009
compatibility_date = "2021-08-23"
compatibility_flags = [
   "formdata_parser_supports_files",
   "streams_enable_constructors",
   "transformstream_enable_standard_constructor",
]
no_bundle = true
r2_buckets = [
   # CAR files live here.
   { binding = "CARPARK", bucket_name = "carpark-staging-0" },
   # Mapping root data CIDs to CAR CID(s).
   { binding = "DUDEWHERE", bucket_name = "dudewhere-staging-0" },
   # CARv2 indexes - a mapping of block offsets within CAR files.
   { binding = "SATNAV", bucket_name = "satnav-staging-0" }
]

[vars]
ENV = "dev"
DEBUG = "true"
DATABASE_URL = "http://localhost:3000"
CARPARK_URL = "https://carpark-dev.web3.storage"
PICKUP_URL = "https://staging.pickup.dag.haus"

[build]
command = "scripts/cli.js build"

# Staging

[env.staging]
name = "nft-storage-staging"
route = "api-staging.nft.storage/*"
usage_model = "unbound"
r2_buckets = [
   { binding = "CARPARK", bucket_name = "carpark-staging-0" },
   { binding = "DUDEWHERE", bucket_name = "dudewhere-staging-0" },
   { binding = "SATNAV", bucket_name = "satnav-staging-0" }
 ]

[env.staging.vars]
ENV = "staging"
DEBUG = "true"
DATABASE_URL = "https://nft-storage-pgrest-staging.herokuapp.com"
CARPARK_URL = "https://carpark-staging.web3.storage"
PICKUP_URL = "https://staging.pickup.dag.haus"

[env.staging.build]
command = "scripts/cli.js build --env staging"
watch_dir = "src"

[env.staging.build.upload]
format = "service-worker"

# Production

[env.production]
name = "nft-storage"
route = "api.nft.storage/*"
usage_model = "unbound"
r2_buckets = [
   { binding = "CARPARK", bucket_name = "carpark-prod-0" },
   { binding = "DUDEWHERE", bucket_name = "dudewhere-prod-0" },
   { binding = "SATNAV", bucket_name = "satnav-prod-0" }
 ]

[env.production.vars]
ENV = "production"
DEBUG = "false"
DATABASE_URL = "https://nft-storage-pgrest-prod.herokuapp.com"
CARPARK_URL = "https://carpark.web3.storage"
PICKUP_URL = "https://pickup.dag.haus"

[env.production.build]
command = "scripts/cli.js build --env production"
watch_dir = "src"

[env.production.build.upload]
format = "service-worker"
