# gateway.nft.storage wrangler config.
name = "gateway-nft-storage"

# `javascript` means our we'll send pre-built javascript code. 
#  ...as opposed to `webpack` where wrangler builds our code for us.
type = "javascript"

account_id = ""
watch_dir = "src"
compatibility_date = "2021-12-03"

[build]
command = "npm run build"
[build.upload]
format = "modules"
dir = "dist"
main = "index.mjs"

[durable_objects]
bindings = [
  {name = "GATEWAYMETRICS", class_name = "GatewayMetrics2"},
  {name = "SUMMARYMETRICS", class_name = "SummaryMetrics3"},
  {name = "CIDSTRACKER", class_name = "CidsTracker0"},
  {name = "GATEWAYRATELIMITS", class_name = "GatewayRateLimits0"},
  {name = "GATEWAYREDIRECTCOUNTER", class_name = "GatewayRedirectCounter2"}
]

# PROD!
[env.production]
# name = "gateway-nft-storage-production"
account_id = "fffa4b4363a7e5250af8357087263b3a" # Protocol Labs CF account
zone_id = "fc6cb51dbc2d0b9a729eae6a302a49c9"    # nft.storage zone
route = "*gateway.nft.storage/*"

[env.production.vars]
IPFS_GATEWAYS = "[\"https://ipfs.io\", \"https://cf-ipfs.com\", \"https://nft-storage.mypinata.cloud/\"]"
DEBUG = "false"
ENV = "production"

[env.production.durable_objects]
bindings = [
  {name = "GATEWAYMETRICS", class_name = "GatewayMetrics2"},
  {name = "SUMMARYMETRICS", class_name = "SummaryMetrics3"},
  {name = "CIDSTRACKER", class_name = "CidsTracker0"},
  {name = "GATEWAYRATELIMITS", class_name = "GatewayRateLimits0"},
  {name = "GATEWAYREDIRECTCOUNTER", class_name = "GatewayRedirectCounter2"}
]

# Staging!
[env.staging]
# name = "gateway-nft-storage-staging"
account_id = "fffa4b4363a7e5250af8357087263b3a" # Protocol Labs CF account
zone_id = "fc6cb51dbc2d0b9a729eae6a302a49c9"    # nft.storage zone
route = "*gateway-staging.nft.storage/*"

[env.staging.vars]
#IPFS_GATEWAYS = "[\"https://ipfs.io\", \"https://cf-ipfs.com\", \"https://nft-storage.mypinata.cloud/\"]"
IPFS_GATEWAYS = "[\"https://ipfs.io\"]"
DEBUG = "true"
ENV = "staging"

[env.staging.durable_objects]
bindings = [
  {name = "GATEWAYMETRICS", class_name = "GatewayMetrics2"},
  {name = "SUMMARYMETRICS", class_name = "SummaryMetrics3"},
  {name = "CIDSTRACKER", class_name = "CidsTracker0"},
  {name = "GATEWAYRATELIMITS", class_name = "GatewayRateLimits0"},
  {name = "GATEWAYREDIRECTCOUNTER", class_name = "GatewayRedirectCounter2"}
]

# Test!
[env.test]
workers_dev = true

[env.test.vars]
IPFS_GATEWAYS = "[\"http://127.0.0.1:9081\", \"http://localhost:9082\", \"http://localhost:9083\"]"
DEBUG = "true"
ENV = "test"

[env.test.durable_objects]
bindings = [
  {name = "GATEWAYMETRICS", class_name = "GatewayMetrics2"},
  {name = "SUMMARYMETRICS", class_name = "SummaryMetrics3"},
  {name = "CIDSTRACKER", class_name = "CidsTracker0"},
  {name = "GATEWAYRATELIMITS", class_name = "GatewayRateLimits0"},
  {name = "GATEWAYREDIRECTCOUNTER", class_name = "GatewayRedirectCounter2"}
]

# Dev!
[env.vsantos]
workers_dev = true
account_id = "7ec0b7cf2ec201b2580374e53ba5f37b"

[env.vsantos.vars]
IPFS_GATEWAYS = "[\"https://ipfs.io\"]"

[env.vsantos.durable_objects]
bindings = [
  {name = "GATEWAYMETRICS", class_name = "GatewayMetrics2"},
  {name = "SUMMARYMETRICS", class_name = "SummaryMetrics3"},
  {name = "CIDSTRACKER", class_name = "CidsTracker0"},
  {name = "GATEWAYRATELIMITS", class_name = "GatewayRateLimits0"},
  {name = "GATEWAYREDIRECTCOUNTER", class_name = "GatewayRedirectCounter2"}
]

[[migrations]]
tag = "v1" # Should be unique for each entry
new_classes = ["GatewayMetrics0", "SummaryMetrics0", "CidsTracker0", "GatewayRateLimits0"]
[[migrations]]
tag = "v2" # Should be unique for each entry
new_classes = ["SummaryMetrics1", "GatewayRedirectCounter0"]
deleted_classes = ["SummaryMetrics0"]
[[migrations]]
tag = "v3" # Should be unique for each entry
renamed_classes = [
  {from = "SummaryMetrics1", to = "SummaryMetrics2" },
  {from = "GatewayRedirectCounter0", to = "GatewayRedirectCounter1" },
  {from = "GatewayMetrics0", to = "GatewayMetrics1" }
]
[[migrations]]
tag = "v4" # Should be unique for each entry
renamed_classes = [
  {from = "SummaryMetrics2", to = "SummaryMetrics3" },
  {from = "GatewayRedirectCounter1", to = "GatewayRedirectCounter2" },
  {from = "GatewayMetrics1", to = "GatewayMetrics2" }
]