name: Cron Pinata Sync

on:
  schedule:
    - cron: '40 */6 * * *'
  workflow_dispatch:

jobs:
  update:
    name: Sync with Pinata
    runs-on: ubuntu-latest
    strategy:
      matrix:
        env: ['production']
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Checkout latest cron release tag
        run: |
          LATEST_TAG=$(git describe --tags --abbrev=0 --match='cron-*')
          git checkout $LATEST_TAG
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - uses: bahmutov/npm-install@v1
      - name: Run job
        env:
          DEBUG: '*'
          ENV: ${{ matrix.env }}
          STAGING_DATABASE_URL: ${{ secrets.STAGING_DATABASE_URL }}
          STAGING_DATABASE_TOKEN: ${{ secrets.STAGING_DATABASE_TOKEN }}
          PROD_DATABASE_URL: ${{ secrets.PROD_DATABASE_URL }}
          PROD_DATABASE_TOKEN: ${{ secrets.PROD_DATABASE_TOKEN }}
          PINATA_JWT: ${{ secrets.PINATA_JWT }}
        run: yarn --cwd packages/cron start:pinata
