name: Manual Deploy
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Choose an environment to deploy API to: <staging|production> (empty for dev)'
        required: false
        default: ''
      frontend_cname:
        description: 'Choose a Cloudflare Pages deployment to point the above environment to, ie: "2f7ade61.nft-storage.pages.dev". This will point <dev|staging>.nft.storage or nft.storage to 2f7ade61.nft-storage.pages.dev. ONLY point production environment to a production deployment.'
        required: false
jobs:
  deploy-api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '18'
      - uses: bahmutov/npm-install@v1
      - name: Publish app
        uses: cloudflare/wrangler-action@1.3.0
        env:
          SENTRY_TOKEN: ${{ secrets.SENTRY_TOKEN}}
          SENTRY_UPLOAD: ${{ secrets.SENTRY_UPLOAD }}
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          workingDirectory: 'packages/api'
          environment: ${{ github.event.inputs.environment }}
      - name: annotation dev
        if: github.event.inputs.environment == ''
        run: echo "::warning::https://api-dev.nft.storage"
      - name: annotation staging
        if: github.event.inputs.environment == 'staging'
        run: echo "::warning::https://api-staging.nft.storage"
      - name: annotation production
        if: github.event.inputs.environment == 'production'
        run: echo "::warning::https://api.nft.storage"
  deploy-frontend-production:
    if: github.event.inputs.environment == 'production'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '18'
      - uses: bahmutov/npm-install@v1
      - run: ./packages/tools/cli.js dns --name classic.nft.storage --token ${{ secrets.CF_API_TOKEN }} --zone ${{ secrets.CF_ZONE }} --content ${{ github.event.inputs.frontend_cname }}
      - run: echo "::warning::https://classic.nft.storage"
  deploy-frontend-staging:
    if: github.event.inputs.environment == 'staging'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '18'
      - uses: bahmutov/npm-install@v1
      - run: ./packages/tools/cli.js dns --name classic-staging.nft.storage --token ${{ secrets.CF_API_TOKEN }} --zone ${{ secrets.CF_ZONE }} --content ${{ github.event.inputs.frontend_cname }}
      - run: echo "::warning::https://classic-staging.nft.storage"
  deploy-frontend-dev:
    if: github.event.inputs.environment == ''
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '18'
      - uses: bahmutov/npm-install@v1
      - run: ./packages/tools/cli.js dns --name dev.nft.storage --token ${{ secrets.CF_API_TOKEN }} --zone ${{ secrets.CF_ZONE }} --content ${{ github.event.inputs.frontend_cname }}
      - run: echo "::warning::https://dev.nft.storage"
