name: Cron Pin ERC-721 Token Assets

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

jobs:
  erc-721:
    name: Pin ERC-721 Assets
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Install dependencies
        run: yarn --cwd packages/niftysave install

      - name: Run job
        env:
          FAUNA_KEY: ${{ secrets.FAUNA_KEY }}
          BATCH_SIZE: 10
          TIME_BUDGET: 1620
          NIFTYSAVE_CLUSTER_KEY: ${{ secrets.NIFTYSAVE_CLUSTER_KEY }}
          NIFTYSAVE_IPFS_API_KEY: ${{ secrets.NIFTYSAVE_IPFS_API_KEY }}
        run: yarn --cwd packages/niftysave import-asset
