name: Cron Analyze ERC-721 Tokens

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch

jobs:
  erc-721:
    name: Analyze ERC-721
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Install dependencies
        run: yarn --cwd packages/niftysave install

      - name: Run job
        env:
          FAUNA_KEY: ${{ secrets.FAUNA_KEY }}
          NIFTYSAVE_CLUSTER_KEY: ${{ secrets.NIFTYSAVE_CLUSTER_KEY }}
          NIFTYSAVE_IPFS_API_KEY: ${{ secrets.NIFTYSAVE_IPFS_API_KEY }}
          BATCH_SIZE: 100
          TIME_BUDGET: 1620
        run: yarn --cwd packages/niftysave import-metadata
